basePath: /
host: http://localhost:8080
info:
  contact: {}
  description: This is the API documentation for the RecycleHub Service.
  title: RecycleHub Service API
  version: "1.0"
paths: {}
schemes:
- https
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
